"""Runs the task's example queries (plus a few more) on the test profiles and writes the real
answers to docs/examples.md, so anyone reading the repo can see what the system says without
running it. Rule-based mode, so it's reproducible:  python -m tests.run_examples
"""
import json
import os
from pathlib import Path

from agent.agent import Recommender
from engine.profile import Profile

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "examples.md"

RUNS = [
    ("cs_2nd_year", ["Suggest DELs related to AI.",
                     "I want an OPEL with no attendance requirement.",
                     "Suggest courses with no midsem and a lenient makeup policy.",
                     "I need a HUEL and prefer project-based evaluation.",
                     "I like finance and economics, any OPEL?",
                     "can I take CS F317 and GS F232 together with no gaps?",
                     "what are my remaining requirements?"]),
    ("ece_3rd_year", ["Suggest an AI-related DEL with no midsem",
                      "Find an OPEL with no attendance requirement",
                      "VLSI electives"]),
    ("chem_3rd_year_nc", ["what's left for me?", "prerequisites of CHE F213"]),
    ("dual_b3a7_3rd_year", ["suggest an OPEL"]),
    ("eee_3rd_year_ds_minor", ["electives related to data science"]),
    ("civil_4th_year_2023", ["DELs related to artificial intelligence or geotechnical engineering", "DELs related to sustainability"]),
]


def main():
    os.environ.pop("ANTHROPIC_API_KEY", None)
    lines = ["# Example runs", "",
             "Generated by `python -m tests.run_examples` in rule-based mode (no API key), on the test profiles in "
             "`tests/profiles/`. Everything below is computed live from the processed data - nothing is hardcoded.",
             ""]
    for prof, queries in RUNS:
        d = json.loads((ROOT / "tests" / "profiles" / f"{prof}.json").read_text())
        p = Profile.from_dict(d)
        rec = Recommender(p, api_key="")
        lines += [f"## {d['name']} - `{d['id_no']}`", "",
                  f"Registered now: {', '.join(d['current']) or 'nothing'} · interests: *{d['interests']}*", ""]
        for q in queries:
            out = rec.ask(q)
            lines += [f"### Q: {q}", "", out["text"], ""]
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines))
    print("wrote", OUT)


if __name__ == "__main__":
    main()
