"""Train / rebuild the course embedding models and write a training report.

    python -m agent.train_embeddings            # both models + evaluation  (~5 s LSA, a few minutes bge on CPU)
    python -m agent.train_embeddings --lsa-only  # just retrain the LSA model

Two models, both built only from the supplied dataset (course titles, Bulletin descriptions, handout
lecture plans):

  1. LSA (agent/semantic.py) - TRAINED here on the ~2,100 course texts: TF-IDF matrix -> SVD, 100 dims.
     Learns BITS's own vocabulary (finance ~ investors / capital / equity).
  2. bge-small-en-v1.5 (agent/embeddings.py) - a pretrained sentence-embedding model, run here over every
     course text to build the embedding index (384-d vectors). The model's weights aren't changed; what's
     built is the index of course vectors it's searched against.

After building, the retrieval evaluation (tests/eval_retrieval.py) is re-run and a short report is written
to docs/embedding_training.md, so every rebuild comes with its numbers.
"""
from __future__ import annotations

import sys
import time
from pathlib import Path

REPORT = Path(__file__).resolve().parent.parent / "docs" / "embedding_training.md"


def main(argv=None):
    argv = argv or sys.argv[1:]
    from agent import semantic
    lines = ["# Embedding training report", "", "Generated by `python -m agent.train_embeddings`.", ""]

    t = time.time()
    lsa = semantic.build()
    lines += ["## 1. LSA model trained on the catalogue (`agent/semantic.py`)", "",
              f"- Courses: {lsa['courses']} · vocabulary: {lsa['vocab']} terms (instructor names removed) · "
              f"latent dimensions: {lsa['dims']}",
              f"- Training time: {time.time() - t:.1f} s · saved to `data/processed/semantic.npz`", ""]
    print("LSA:", lsa)

    lines += ["## 2. Sentence-embedding index, bge-small-en-v1.5 (`agent/embeddings.py`)", ""]
    if "--lsa-only" in argv:
        lines += ["- Skipped (`--lsa-only`); the committed `data/processed/embeddings.npz` is kept.", ""]
    else:
        try:
            from agent import embeddings
            t = time.time()
            emb = embeddings.build()
            lines += [f"- Model: `{emb['model']}` (pretrained, ONNX Runtime via fastembed, no PyTorch)",
                      f"- Courses embedded: {emb['courses']} · dimensions: {emb['dims']}",
                      f"- Build time: {time.time() - t:.0f} s · saved to `data/processed/embeddings.npz`", ""]
            print("embeddings:", emb)
        except ImportError:
            lines += ["- fastembed isn't installed; the committed `data/processed/embeddings.npz` is kept.", ""]

    # fresh models -> fresh caches, then evaluate
    from agent import embeddings as E, retrieval as R, semantic as S
    S.get_semantic.cache_clear()
    E.get_embeddings.cache_clear()
    R.topic_groups.cache_clear()
    R._group_embedding_centroids.cache_clear()
    from tests import eval_retrieval
    eval_retrieval.main()
    ev = eval_retrieval.OUT.read_text().splitlines()
    table = [l for l in ev if l.startswith("|")][:7]
    found = next((l for l in ev if l.startswith("**Group found")), "")
    lines += ["## 3. Evaluation (full results in [retrieval_eval.md](retrieval_eval.md))", "",
              "Ranking: each Bulletin minor's name as the query, its courses as the answers, all 582 offered courses "
              "ranked.", ""] + table + ["", f"Plain-English topics: {found.strip('*')}", ""]
    REPORT.write_text("\n".join(lines) + "\n")
    print("wrote", REPORT)


if __name__ == "__main__":
    main()
